import shutil

import pytest

import arcadia_pycolor as apc


def pytest_addoption(parser):
    """
    Add custom CLI options for pytest.

    Note: this function is a pytest hook and it must appear in a file named `conftest.py`
    in the root directory of the project.
    """
    parser.addoption(
        "--output-dirpath",
        dest="output_dirpath",
        default=None,
        help="Path to a directory in which to save the plots generated by the tests.",
    )


@pytest.fixture(scope="session", autouse=True)
def setup_matplotlib():
    apc.mpl.setup()


@pytest.fixture(scope="session")
def output_dirpath(pytestconfig, tmp_path_factory):
    """
    Return the path to the directory in which to save the output of the tests.
    """
    tmp_path = tmp_path_factory.mktemp("output")

    yield tmp_path

    user_provided_output_dirpath = pytestconfig.getoption("output_dirpath")
    if user_provided_output_dirpath is not None:
        shutil.rmtree(user_provided_output_dirpath)
        shutil.copytree(tmp_path, user_provided_output_dirpath)
