# Copied from: https://squidfunk.github.io/mkdocs-material/publishing-your-site/.
name: Deploy MkDocs site
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        # Fetching the full git history is necessary because poetry's dynamic versioning extension
        # requires it, and this extension is run even when the package is pip-installed locally
        # (as we do below).
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.8.3-0

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        id: cache-deps-2025-05-29
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root --with=dev
        if: steps.cache-deps-2025-05-29.outputs.cache-hit != 'true'

      - name: Install arcadia-pycolor
        run: poetry run pip install .

      - name: Deploy MkDocs site
        run: poetry run mkdocs gh-deploy --force
